[project]
name = "elderly-care-agent"
version = "0.1.0"
description = "AI-powered elderly care agent with voice support"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk>=1.17.0",
    "fastapi>=0.120.0",
    "uvicorn[standard]>=0.38.0",
    "python-dotenv>=1.2.0",
]
